[package]
name = "prgpu"
version = "0.1.0"
edition = "2024"

[features]
default = ["metal", "cargo-clippy"] # build with no GPU backend by default
cuda = ["cudarc"]                   # enable CUDA backend
metal = []                          # enable Metal backend
cargo-clippy = []
shader_hotreload = []               # enable shader hot-reloading (for development only)

[dependencies]
after-effects = { git = "https://github.com/Exaecut/after-effects.git", branch = "master", features = [
    "catch-panics",
] }
premiere = { git = "https://github.com/Exaecut/after-effects.git", branch = "master" }
bytemuck = "1.23.1"
parking_lot = "0.12.3"

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2.7" }
cudarc = { version = "0.17.3", features = ["cuda-12050"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
cudarc = { version = "0.17.3", features = ["cuda-12050"], optional = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(shader_hotreload)",
    "cfg(does_dialog)",
    "cfg(with_premiere)",
    "cfg(threaded_rendering)",
] }
