import shutil
from pathlib import Path

dest = Path(r'C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\Exaecut')
dest.mkdir(parents=True, exist_ok=True)

built = [{'platform': 'windows', 'name': 'chromaticaberration', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\chromaticaberration.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\chromaticaberration.pdb'}, {'platform': 'windows', 'name': 'echo', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\echo.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\echo.pdb'}, {'platform': 'windows', 'name': 'godrays', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\godrays.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\godrays.pdb'}, {'platform': 'windows', 'name': 'hueshift', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\hueshift.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\hueshift.pdb'}, {'platform': 'windows', 'name': 'milkshake', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\milkshake.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\milkshake.pdb'}, {'platform': 'windows', 'name': 'mindglow', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\mindglow.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\mindglow.pdb'}, {'platform': 'windows', 'name': 'pixelsort', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\pixelsort.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\pixelsort.pdb'}, {'platform': 'windows', 'name': 'plasmawaves', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\plasmawaves.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\plasmawaves.pdb'}, {'platform': 'windows', 'name': 'radialblur', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\radialblur.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\radialblur.pdb'}, {'platform': 'windows', 'name': 'retrovhs', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\retrovhs.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\retrovhs.pdb'}, {'platform': 'windows', 'name': 'vignette', 'aex': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\vignette.aex', 'pdb': 'C:\\Users\\Marvin\\Documents\\Projects\\Exaecut\\effects\\target\\debug\\vignette.pdb'}]

for item in built:
    aex = Path(item['aex'])
    pdb = Path(item['pdb'])
    if aex.exists(): shutil.copy2(aex, dest / f"{item['name']}.aex")
    if pdb.exists(): shutil.copy2(pdb, dest / f"{item['name']}.pdb")
